### ISSUE TITLE
Comet could not be found

### ISSUE THREAD

**Issue by titonton** [Clancey/Comet#182]
After following the Getting Started docs, AppDelegate.cs cannot seem to find the Comet package. is it supposed to be a separate package to be installed or is it part of the Comet package?

**Comment by titonton** [comment]
I think I just fixed it by explicitly adding a reference to it in the csproj file.

**Comment by Clancey** [comment]
It sounds like the Nuget didn’t Restore. If you’re doing it in VSCode you may need to manually restore via the command line

**Comment by jarendt** [comment]
I had the same issue. The workaround that worked for me was to open the sln in VS for Mac. All nugets properly restored. Then I was able to use the sln in VS code.

It is reproducible by clearing the local nuget caches. Try to load in VS code and it would fail again. Trying to restore packages via VS code or terminal (i.e. dotnet restore) would fail to restore all packages. Repeat the workaround to restore in VS for Mac and I was good in both tools for building.

**Comment by Clancey** [comment]
Using ‘nuget restore’ works from the terminal or VSCode terminal

**Comment by jarendt** [comment]
The Getting Started guide (https://github.com/Clancey/Comet/wiki/Getting-Started) references **dotnet restore** and _not_ **nuget restore**. The two commands behave differently on the project. That explains the different with why VS for Mac works around the issue since it does the equivalent of **nuget restore** for a Xamarin project.

When I dug into why the iOS project was not restoring before seeing your response, I saw it was skipping restoring because **dotnet restore** looks in a different MSBuildExtensionsPath which causes it to not find the Xamarin.iOS.CSharp.targets file.

Using **nuget restore** addresses this issue for a clean system.

**Comment by titonton** [comment]
Interesting. Thanks for the research @jarendt and thank you for your reply @Clancey.
